_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java
       case 0:  // PortableActivationIDL/InitialNameService/bind

  /** bind initial name
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java
public abstract class _InitialNameServiceImplBase extends org.omg.CORBA.portable.ObjectImpl

/** Interface used to support binding references in the bootstrap name
    * service.
    */
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java


/**
* com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_InitialNameServiceImplBase.java
public abstract class _InitialNameServiceImplBase extends org.omg.CORBA.portable.ObjectImpl

/**
* com/sun/corba/se/spi/activation/_InitialNameServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/
