_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 8:  // PortableActivationIDL/Repository/getServerID

  /** Find the ServerID associated with the given application name.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 7:  // PortableActivationIDL/Repository/getApplicationNames

  /** Returns list of ALL applicationNames defined in ServerDefs of registered 
	* servers.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 6:  // PortableActivationIDL/Repository/listRegisteredServers

  /** list registered servers
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 5:  // PortableActivationIDL/Repository/uninstall

  /** Mark the server as being uninstalled.  Raises ServerAlreadyUninstalled
	* if the server is currently marked as uninstalled.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 4:  // PortableActivationIDL/Repository/install

  /** Mark the server as being installed.  Raises ServerAlreadyInstalled
	* if the server is currently marked as installed.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 3:  // PortableActivationIDL/Repository/isInstalled

  /** Return whether the server has been installed
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 2:  // PortableActivationIDL/Repository/getServer

  /** get server definition
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 1:  // PortableActivationIDL/Repository/unregisterServer

  /** unregister server definition
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java
       case 0:  // PortableActivationIDL/Repository/registerServer

  /** register server definition.
	* This returns the serverId of the server.  A newly created server is
	* always uninstalled.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java


/**
* com/sun/corba/se/PortableActivationIDL/_RepositoryImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_RepositoryImplBase.java
public abstract class _RepositoryImplBase extends org.omg.CORBA.portable.ObjectImpl

/**
* com/sun/corba/se/spi/activation/_RepositoryImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/
