_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_ServerImplBase.java
       case 2:  // activation/Server/uninstall

  /** Uninstall the server.  Returns after the uninstall hook
	* completes execution.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_ServerImplBase.java
       case 1:  // activation/Server/install

  /** Install the server.  Returns after the install hook completes
	* execution in the server.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_ServerImplBase.java
       case 0:  // activation/Server/shutdown

  /** Shutdown this server.  Returns after orb.shutdown() completes.
	*/
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_ServerImplBase.java
public abstract class _ServerImplBase extends org.omg.CORBA.portable.ObjectImpl

/** Server callback API, passed to Activator in active method.
    */
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/_ServerImplBase.java


/**
* com/sun/corba/se/spi/activation/_ServerImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/
