_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/imageio/plugins/jpeg/DQTMarkerSegment.java
        private final int [] zigzag = {

        /**
         * The zigzag-order position of the i'th element
         * of a DCT block read in natural order.
         */
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/imageio/plugins/jpeg/DQTMarkerSegment.java
    class Qtable implements Cloneable {

    /**
     * A quantization table within a DQT marker segment.
     */
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/imageio/plugins/jpeg/DQTMarkerSegment.java
    Qtable getChromaForLuma(Qtable luma) {

    /**
     * Assuming the given table was generated by scaling the "standard"
     * visually lossless luminance table, extract the scale factor that
     * was used.
     */
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/imageio/plugins/jpeg/DQTMarkerSegment.java
    void write(ImageOutputStream ios) throws IOException {

    /**
     * Writes the data for this segment to the stream in
     * valid JPEG format.
     */
_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/imageio/plugins/jpeg/DQTMarkerSegment.java
class DQTMarkerSegment extends MarkerSegment {

/**
 * A DQT (Define Quantization Table) marker segment.
 */
