_func_
java
c:/Users/Saahil/OneDrive/Code/EmacsPackage/jdksource//com/sun/corba/se/spi/activation/RepositoryPackage/StringSeqHolder.java
public final class StringSeqHolder implements org.omg.CORBA.portable.Streamable

/**
* com/sun/corba/se/spi/activation/RepositoryPackage/StringSeqHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/re/workspace/8-2-build-windows-amd64-cygwin/jdk8u45/3627/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Thursday, April 30, 2015 12:42:08 PM PDT
*/
