_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java
       case 0:  // PortableActivationIDL/InitialNameService/bind

  /** bind initial name
	*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java
public abstract class _InitialNameServiceImplBase extends org.omg.CORBA.portable.ObjectImpl

/** Interface used to support binding references in the bootstrap name
    * service.
    */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java


/**
* com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/spi/activation/_InitialNameServiceImplBase.java
public abstract class _InitialNameServiceImplBase extends org.omg.CORBA.portable.ObjectImpl

/**
* com/sun/corba/se/spi/activation/_InitialNameServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java
       case 0:  // PortableActivationIDL/InitialNameService/bind

  /** bind initial name
	*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java
public abstract class _InitialNameServiceImplBase extends org.omg.CORBA.portable.ObjectImpl

/** Interface used to support binding references in the bootstrap name
    * service.
    */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java


/**
* com/sun/corba/se/PortableActivationIDL/_InitialNameServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/spi/activation/_InitialNameServiceImplBase.java
public abstract class _InitialNameServiceImplBase extends org.omg.CORBA.portable.ObjectImpl

/**
* com/sun/corba/se/spi/activation/_InitialNameServiceImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
