_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/_PolicyStub.java
  public void destroy ()

  /** Destroys the policy object.  It is the responsibility of
                * the policy object to determine whether it can be destroyed.
                */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/_PolicyStub.java
  public org.omg.CORBA.Policy copy ()

  /** Copies the policy object. The copy does not retain any
                * relationships that the policy had with any domain or object.
                * @return the copy of the policy object.
                */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/_PolicyStub.java
  public int policy_type ()

  /** Returns the constant value that corresponds to the
                * type of the policy object.  The values of
                * the polivy objectys are allocated by the OMG.
                * New values for PolicyType should be obtained from the OMG by
                * sending mail to request@omg.org.  In general the constant
                * values that are allocated are defined in conjunction with
                * the definition of the corresponding policy object.
                * @return the constant value that corresponds to the type of
                * the policy object.
                */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/_PolicyStub.java
  public _PolicyStub (org.omg.CORBA.portable.Delegate delegate)

  /** Constructs a <code>_PolicyStub</code> object initialized
   * with the given <code>Delegate</code> object.
   *
   * @param delegate a Delegate Object
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/_PolicyStub.java
  public _PolicyStub ()

  /** Constructors
   * NOTE:  If the default constructor is used, the
   *        object is useless until _set_delegate (...)
   *        is called.
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/_PolicyStub.java
public class _PolicyStub extends org.omg.CORBA.portable.ObjectImpl implements org.omg.CORBA.Policy

/**
* The Stub for <tt>Policy</tt>.  For more information on
* Stub files, see <a href="doc-files/generatedfiles.html#stub">
* "Generated Files: Stubs"</a>.<P>
* org/omg/CORBA/_PolicyStub.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl.
* Saturday, July 17, 1999 12:26:20 AM PDT
*/
