_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableInterceptor/AdapterStateHelper.java
abstract public class AdapterStateHelper

/** Type of object adapter state.  State changes are reported either to
   * the object adapter or to the adapter manager.
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableInterceptor/AdapterStateHelper.java


/**
* org/omg/PortableInterceptor/AdapterStateHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
