_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingIteratorOperations.java
  void destroy ();

  /**
     * This operation destroys the iterator.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingIteratorOperations.java
  boolean next_n (int how_many, org.omg.CosNaming.BindingListHolder bl);

  /**
     * This operation returns at most the requested number of bindings.
     * 
     * @param how_many the maximum number of bindings tro return <p>
     * 
     * @param bl the returned bindings
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingIteratorOperations.java
  boolean next_one (org.omg.CosNaming.BindingHolder b);

  /**
     * This operation returns the next binding. If there are no more
     * bindings, false is returned.
     * 
     * @param b the returned binding
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingIteratorOperations.java
public interface BindingIteratorOperations 

/**
   * The BindingIterator interface allows a client to iterate through
   * the bindings using the next_one or next_n operations.
   * 
   * The bindings iterator is obtained by using the <tt>list</tt>
   * method on the <tt>NamingContext</tt>. 
   * @see org.omg.CosNaming.NamingContext#list
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingIteratorOperations.java


/**
* org/omg/CosNaming/BindingIteratorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
