_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingTypeHelper.java
abstract public class BindingTypeHelper

/**
   * Specifies whether the given binding is for a object (that is not a
   * naming context) or for a naming context.
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingTypeHelper.java


/**
* org/omg/CosNaming/BindingTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
