_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//javax/xml/ws/BindingType.java
     String value() default "" ;

     /**
      * A binding identifier (a URI).
      * If not specified, the default is the SOAP 1.1 / HTTP binding.
      * <p>
      * See the <code>SOAPBinding</code> and <code>HTTPBinding</code>
      * for the definition of the standard binding identifiers.
      *
      * @see javax.xml.ws.Binding
      * @see javax.xml.ws.soap.SOAPBinding#SOAP11HTTP_BINDING
      * @see javax.xml.ws.soap.SOAPBinding#SOAP12HTTP_BINDING
      * @see javax.xml.ws.http.HTTPBinding#HTTP_BINDING
      */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//javax/xml/ws/BindingType.java
@Target(ElementType.TYPE)

/**
 *  The <code>BindingType</code> annotation is used to
 *  specify the binding to use for a web service
 *  endpoint implementation class.
 *  <p>
 *  This annotation may be overriden programmatically or via
 *  deployment descriptors, depending on the platform in use.
 *
 *  @since JAX-WS 2.0
 *
 **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingType.java
public class BindingType implements org.omg.CORBA.portable.IDLEntity

/**
   * Specifies whether the given binding is for a object (that is not a
   * naming context) or for a naming context.
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/BindingType.java


/**
* org/omg/CosNaming/BindingType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
