_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/CodecFactoryHelper.java
abstract public class CodecFactoryHelper

/**
   * <code>Codecs</code> are obtained from the <code>CodecFactory</code>. 
   * The <code>CodecFactory</code> is obtained through a call to 
   * <code>ORB.resolve_initial_references( "CodecFactory" )</code>.
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/CodecFactoryHelper.java


/**
* org/omg/IOP/CodecFactoryHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
