_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/CodeSets.java
  public static final int value = (int)(1L);

  /**
     * Identifies a CDR encapsulation of the 
     * <code>CONV_FRAME.CodeSetContext</code> defined in 
     * Section 13.10.2.5, "GIOP Code Set Service Context," on page 13-43.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/CodeSets.java


/**
* org/omg/IOP/CodeSets.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
