_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/ComponentIdHelper.java
abstract public class ComponentIdHelper

/**
     * Standard way of representing multicomponent profiles.
     * This would be encapsulated in a TaggedProfile.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/ComponentIdHelper.java


/**
* org/omg/IOP/ComponentIdHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
