_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/CompletionStatusHelper.java
abstract public class CompletionStatusHelper

/**
* The Helper for <tt>CompletionStatus</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* org/omg/CORBA/CompletionStatusHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* 03 June 1999 11:52:03 o'clock GMT+00:00
*/
