_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/CurrentHolder.java
public final class CurrentHolder implements org.omg.CORBA.portable.Streamable

/**
* The Holder for <tt>Current</tt>.  For more information on
* Holder files, see <a href="doc-files/generatedfiles.html#holder">
* "Generated Files: Holder Files"</a>.<P>
* org/omg/CORBA/CurrentHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:21 AM PDT
*/
