_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynStruct.java
    public void set_members(org.omg.CORBA.NameValuePair[] value)

    /**
     * Set the members of the struct.
     *
     * @param value the array of name-value pairs.
         * @throws org.omg.CORBA.DynAnyPackage.InvalidSeq if the given argument
         *         is invalid
         * @see #get_members
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynStruct.java
    public org.omg.CORBA.NameValuePair[] get_members();

    /**
     * Returns an array containing all the members of the stored struct.
     *
     * @return the array of name-value pairs
         * @see #set_members
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynStruct.java
    public org.omg.CORBA.TCKind current_member_kind();

    /**
     * Returns the <code>TCKind</code> object that describes the kind of
         * the current member.
     *
     * @return the <code>TCKind</code> object that describes the current member
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynStruct.java
    public String current_member_name();

    /**
     * During a traversal, returns the name of the current member.
     *
     * @return the string name of the current member
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynStruct.java
@Deprecated

/**
 * The representation of a <code>DynAny</code> object that is associated
 *  with an IDL struct.
 * @deprecated Use the new <a href="../DynamicAny/DynStruct.html">DynStruct</a> instead
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/DynStruct.java
public interface DynStruct extends DynStructOperations, org.omg.DynamicAny.DynAny, org.omg.CORBA.portable.IDLEntity 

/**
    * DynStruct objects support the manipulation of IDL struct and exception values.
    * Members of the exceptions are handled in the same way as members of a struct.
    */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/DynStruct.java


/**
* org/omg/DynamicAny/DynStruct.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
