_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/Encoding.java
  public byte minor_version = (byte)0;

  /**
     * The minor version of this Encoding format.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/Encoding.java
  public byte major_version = (byte)0;

  /**
     * The major version of this Encoding format.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/Encoding.java
  public short format = (short)0;

  /**
     * The encoding format.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/Encoding.java


/**
* org/omg/IOP/Encoding.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
