_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ImplicitActivationPolicyValue.java
public class ImplicitActivationPolicyValue implements org.omg.CORBA.portable.IDLEntity

/**
	 * ImplicitActivationPolicyValue has the following
	 * semantics.
	 * IMPLICIT_ACTIVATION to indicate implicit activation
	 * of servants.  This requires SYSTEM_ID and RETAIN 
	 * policies to be set.
	 * NO_IMPLICIT_ACTIVATION to indicate no implicit 
	 * servant activation.
	 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ImplicitActivationPolicyValue.java


/**
* org/omg/PortableServer/ImplicitActivationPolicyValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
