_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ORBPackage/InconsistentTypeCode.java
    public InconsistentTypeCode(String reason) {

    /**
    * Constructs an <code>InconsistentTypeCode</code> user exception
    * with the specified reason message.
    * @param reason The String containing a reason message
    */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ORBPackage/InconsistentTypeCode.java
    public InconsistentTypeCode() {

    /**
     * Constructs an <code>InconsistentTypeCode</code> user exception
     * with no reason message.
    */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ORBPackage/InconsistentTypeCode.java
public final class InconsistentTypeCode

/**
 * InconsistentTypeCode is thrown when an attempt is made to create a
 * dynamic any with a type code that does not match the particular
 * subclass of <code>DynAny</code>.
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/DynAnyFactoryPackage/InconsistentTypeCode.java
public final class InconsistentTypeCode extends org.omg.CORBA.UserException

/**
* org/omg/DynamicAny/DynAnyFactoryPackage/InconsistentTypeCode.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
