_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynAnyPackage/InvalidValue.java
    public InvalidValue(String reason) {

    /**
     * Constructs an <code>InvalidValue</code> object.
     * @param reason  a <code>String</code> giving more information
     * regarding the exception.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynAnyPackage/InvalidValue.java
    public InvalidValue() {

    /**
     * Constructs an <code>InvalidValue</code> object.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/DynAnyPackage/InvalidValue.java
public final class InvalidValue

/**
 * @author unattributed
 *
 * Dynamic Any insert operations raise the <code>InvalidValue</code>
 * exception if the value inserted is not consistent with the type
 * of the accessed component in the <code>DynAny</code> object.
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/DynAnyPackage/InvalidValue.java
public final class InvalidValue extends org.omg.CORBA.UserException

/**
* org/omg/DynamicAny/DynAnyPackage/InvalidValue.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
