_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ORBPackage/InvalidName.java
    public InvalidName(String reason) {

    /**
     * Constructs an <code>InvalidName</code> exception with the specified
     * reason message.
     * @param reason the String containing a reason message
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ORBPackage/InvalidName.java
final public class InvalidName extends org.omg.CORBA.UserException {

/**
 * The <code>InvalidName</code> exception is raised when
 * <code>ORB.resolve_initial_references</code> is passed a name
 * for which there is no initial reference.
 *
 * @see org.omg.CORBA.ORB#resolve_initial_references(String)
 * @since   JDK1.2
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/NamingContextPackage/InvalidName.java
public final class InvalidName extends org.omg.CORBA.UserException

/**
* org/omg/CosNaming/NamingContextPackage/InvalidName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableInterceptor/ORBInitInfoPackage/InvalidName.java
public final class InvalidName extends org.omg.CORBA.UserException

/**
* org/omg/PortableInterceptor/ORBInitInfoPackage/InvalidName.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
