_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/NamingContextPackage/InvalidNameHelper.java
abstract public class InvalidNameHelper

/**
* org/omg/CosNaming/NamingContextPackage/InvalidNameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableInterceptor/ORBInitInfoPackage/InvalidNameHelper.java
abstract public class InvalidNameHelper

/**
* org/omg/PortableInterceptor/ORBInitInfoPackage/InvalidNameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
