_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/NameValuePairHelper.java
abstract public class NameValuePairHelper

/**
* The Helper for <tt>NameValuePair</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* org/omg/CORBA/NameValuePairHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* 03 June 1999 11:52:03 o'clock GMT+00:00
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameValuePairHelper.java
abstract public class NameValuePairHelper

/**
* org/omg/DynamicAny/NameValuePairHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
