_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/NameHolder.java
public final class NameHolder implements org.omg.CORBA.portable.Streamable

/**
   * A name is a sequence of name components.
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/NameHolder.java


/**
* org/omg/CosNaming/NameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
