_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameDynAnyPair.java
  public org.omg.DynamicAny.DynAny value = null;

  /**
        * The DynAny value associated with the name.
        */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameDynAnyPair.java
  public String id = null;

  /**
        * The name associated with the DynAny.
        */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameDynAnyPair.java


/**
* org/omg/DynamicAny/NameDynAnyPair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
