_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/NameValuePair.java
    public NameValuePair(String __id, org.omg.CORBA.Any __value) {

    /**
     * Constructs a <code>NameValuePair</code> object that associates
     * the given name with the given <code>org.omg.CORBA.Any</code> object.
     * @param __id the name to be associated with the given <code>Any</code> object
     * @param __value the <code>Any</code> object to be associated with the given name
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/NameValuePair.java
    public NameValuePair() { }

    /**
     * Constructs an empty <code>NameValuePair</code> object.
     * To associate a name with a value after using this constructor, the fields
     * of this object have to be accessed individually.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/NameValuePair.java
    public org.omg.CORBA.Any value;

    /**
     * The value to be associated with a name by this <code>NameValuePair</code> object.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/NameValuePair.java
    public String id;

    /**
     * The name to be associated with a value by this <code>NameValuePair</code> object.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/NameValuePair.java
public final class NameValuePair implements org.omg.CORBA.portable.IDLEntity {

/**
 * Associates  a name with a value that is an
 * attribute of an IDL struct, and is used in the <tt>DynStruct</tt> APIs.
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameValuePair.java
  public org.omg.CORBA.Any value = null;

  /**
        * The Any value associated with the name.
        */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameValuePair.java
  public String id = null;

  /**
        * The name associated with the Any.
        */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/DynamicAny/NameValuePair.java


/**
* org/omg/DynamicAny/NameValuePair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/DynamicAny/DynamicAny.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
