_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ParameterModeHelper.java
abstract public class ParameterModeHelper

/**
   * Enumeration of parameter modes for Parameter.  Possible vaues:
   * <ul>
   *   <li>PARAM_IN - Represents an "in" parameter.</li>
   *   <li>PARAM_OUT - Represents an "out" parameter.</li>
   *   <li>PARAM_INOUT - Represents an "inout" parameter.</li>
   * </ul>
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/ParameterModeHelper.java


/**
* org/omg/CORBA/ParameterModeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
