_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/POAHelper.java
/**

/**
* org/omg/PortableServer/POAHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from ../../../../src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 23, 2001 1:16:58 PM PDT
*/
