_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/PolicyErrorHelper.java
abstract public class PolicyErrorHelper

/**
   * Thrown to indicate problems with parameter values passed to the
   * <code>ORB.create_policy</code> operation.  
   */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/PolicyErrorHelper.java


/**
* org/omg/CORBA/PolicyErrorHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
