_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/PolicyListHelper.java
abstract public class PolicyListHelper

/**
* The Helper for <tt>PolicyList</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* org/omg/CORBA/PolicyListHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:21 AM PDT
*/
