_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/PolicyTypeHelper.java
// basic Policy definition

/**
* The Helper for <tt>PolicyType</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* org/omg/CORBA/PolicyTypeHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../src/share/classes/org/omg/PortableServer/corba.idl
* Saturday, July 17, 1999 12:26:20 AM PDT
*/
