_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/impl/protocol/giopmsgheaders/ProfileAddr.java
public interface ProfileAddr

/**
* com/sun/corba/se/impl/protocol/giopmsgheaders/ProfileAddr.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../../../src/share/classes/com/sun/corba/se/GiopIDL/g.idl
* Sunday, June 4, 2000 5:18:54 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/impl/protocol/giopmsgheaders/ProfileAddr.java
public interface ProfileAddr

/**
* com/sun/corba/se/impl/protocol/giopmsgheaders/ProfileAddr.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ../../../../../../../src/share/classes/com/sun/corba/se/GiopIDL/g.idl
* Sunday, June 4, 2000 5:18:54 PM PDT
*/
