_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java
  public static final int value = (int)(22L);

  /**
	 * The value representing REQUEST_PROCESSING_POLICY_ID.
	 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
