_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/RMICustomMaxStreamFormat.java
  public static final int value = (int)(17L);

  /**
     * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
     * service context which contains a single byte specifying
     * the client's maximum RMI-IIOP stream format version.
     *
     * See Java to IDL ptc/02-01-12 1.4.12.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/RMICustomMaxStreamFormat.java


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
