_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//java/text/RuleBasedCollationKey.java
    RuleBasedCollationKey(String source, String key) {

    /**
     * A RuleBasedCollationKey can only be generated by Collator objects.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//java/text/RuleBasedCollationKey.java
    public byte[] toByteArray() {

    /**
     * Converts the RuleBasedCollationKey to a sequence of bits. If two RuleBasedCollationKeys
     * could be legitimately compared, then one could compare the byte arrays
     * for each of those keys to obtain the same result.  Byte arrays are
     * organized most significant byte first.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//java/text/RuleBasedCollationKey.java
    public int hashCode() {

    /**
     * Creates a hash code for this RuleBasedCollationKey. The hash value is calculated on the
     * key itself, not the String from which the key was created.  Thus
     * if x and y are RuleBasedCollationKeys, then x.hashCode(x) == y.hashCode() if
     * x.equals(y) is true.  This allows language-sensitive comparison in a hash table.
     * See the CollatinKey class description for an example.
     * @return the hash value based on the string's collation order.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//java/text/RuleBasedCollationKey.java
    public boolean equals(Object target) {

    /**
     * Compare this RuleBasedCollationKey and the target for equality.
     * The collation rules of the Collator object which created these keys are applied.
     * <strong>Note:</strong> RuleBasedCollationKeys created by different Collators can not be
     * compared.
     * @param target the RuleBasedCollationKey to compare to.
     * @return Returns true if two objects are equal, false otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//java/text/RuleBasedCollationKey.java
final class RuleBasedCollationKey extends CollationKey {

/**
 * A RuleBasedCollationKey is a concrete implementation of CollationKey class.
 * The RuleBasedCollationKey class is used by the RuleBasedCollator class.
 */
