_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ServantRetentionPolicyOperations.java
  org.omg.PortableServer.ServantRetentionPolicyValue value ();

  /**
	 * specifies the policy value
	 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ServantRetentionPolicyOperations.java
public interface ServantRetentionPolicyOperations  extends org.omg.CORBA.PolicyOperations

/**
	 * This policy specifies whether the created POA retains 
	 * active servants in an Active Object Map. 
	 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ServantRetentionPolicyOperations.java


/**
* org/omg/PortableServer/ServantRetentionPolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
