_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/LocatorPackage/ServerLocationPerTypeHolder.java
public final class ServerLocationPerTypeHolder implements org.omg.CORBA.portable.Streamable

/**
* com/sun/corba/se/PortableActivationIDL/LocatorPackage/ServerLocationPerTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/PortableActivationIDL/LocatorPackage/ServerLocationPerTypeHolder.java
public final class ServerLocationPerTypeHolder implements org.omg.CORBA.portable.Streamable

/**
* com/sun/corba/se/PortableActivationIDL/LocatorPackage/ServerLocationPerTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/PortableActivationIDL/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
