_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    private void setValueValid() {

    /**
     * Sets the status to indicate that the value for this <CODE>SnmpVarBind</CODE> is valid.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    @Override

     /**
     * Returns the printable ASCII representation of this <CODE>SnmpVarBind</CODE>.
     * @return The printable ASCII representation.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setEndOfMibView() {

    /**
     * Set the value to {@link #endOfMibView}. This is equivalent to
     * <code>setSnmpValue(SnmpVarBind.endOfMibView)</code>.
     **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setNoSuchInstance() {

    /**
     * Set the value to {@link #noSuchInstance}. This is equivalent to
     * <code>setSnmpValue(SnmpVarBind.noSuchInstance)</code>.
     **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setNoSuchObject() {

    /**
     * Set the value to {@link #noSuchObject}. This is equivalent to
     * <code>setSnmpValue(SnmpVarBind.noSuchObject)</code>.
     **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public String getStringValue() {

    /**
     * Returns the printable ASCII representation for the corresponding variable value.
     * @return The printable ASCII representation.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    @Override

    /**
     * Clones the SNMP variable (including value).
     * @return The SNMP variable clone.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public Object cloneWithoutValue() {

    /**
     * Clones the SNMP variable. It does not clone the value portion.
     * @return A new object with the value part set to null.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void copyValue(SnmpVarBind var) {

    /**
     * Clones and copies only the value part from another <CODE>SnmpVarBind</CODE> object.
     * @param var The <CODE>SnmpVarBind</CODE> clone.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void copyValueAndOid(SnmpVarBind var) {

    /**
     * Clones and copies the OID and value part from another <CODE>SnmpVarBind</CODE> object.
     * @param var The <CODE>SnmpVarBind</CODE> clone.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public synchronized boolean hasVarBindException() {

    /**
     * Determines whether the <CODE>SnmpVarBind</CODE> has an SNMP exception
     * (generated by agent in response to a request).
     * @return <CODE>true</CODE> if the <CODE>SnmpVarBind</CODE> has an SNMP response exception,
     * <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void appendInOid(SnmpOid oid) {

    /**
     * Appends the specified <CODE>SnmpOid</CODE> to the end of the OID of this <CODE>SnmpVarBind</CODE>.
     * @param oid The OID to append.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void insertInOid(int oid) {

    /**
     * Inserts a sub-id at the beginning of the OID of this <CODE>SnmpVarBind</CODE>.
     * @param oid The sub-id to insert.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void addInstance(String inst) throws SnmpStatusException {

    /**
     * Adds an instance part to the OID in the <CODE>SnmpOid</CODE> object.
     * Note that there is no <CODE>getInstance</CODE> method.
     * This method will directly add the instance to the <CODE>SnmpOid</CODE> object.
     * @param inst Dot-formatted sub-identifier <CODE>String</CODE> to be appended to the OID.
     * @exception SnmpStatusException An error occurred while accessing a MIB node.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void addInstance(long[] inst) throws SnmpStatusException {

    /**
     * Adds an instance part to the OID in the <CODE>SnmpOid</CODE> object.
     * Note that there is no <CODE>getInstance</CODE> method.
     * This method will directly add the instance to the <CODE>SnmpOid</CODE> object.
     * @param inst The sub-identifier array to be appended to the OID.
     * @exception SnmpStatusException An error occurred while accessing a MIB node.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void addInstance(long inst) {

    /**
     * Adds an instance part to the OID in the <CODE>SnmpOid</CODE> object.
     * Note that there is no <CODE>getInstance</CODE> method.
     * This method will directly add the instance to the <CODE>SnmpOid</CODE> object.
     * @param inst The sub-identifier to be appended to the OID.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public boolean isOidEqual(SnmpVarBind var) {

    /**
     * Checks whether the OID for this variable completely matches the OID part of the specified
     * <CODE>SnmpVarBind</CODE> object.
     * @param var The object whose OID part is to be matched.
     * @return <CODE>true</CODE> if the OID part matches exactly, <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void clearValue() {

    /**
     * Clears the value associated with this <CODE>SnmpVarBind</CODE> and sets the status to
     * <CODE>stValueUnspecified</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public boolean isUnspecifiedValue() {

    /**
     * Checks whether the value associated with this <CODE>SnmpVarBind</CODE> is unspecified.
     * @return <CODE>true</CODE> if the status is unspecified, <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public boolean isValidValue() {

    /**
     * Checks whether the object contains a valid accessible value.
     * @return <CODE>true</CODE> if the associated value is valid, <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public String getValueStatusLegend() {

    /**
     * Returns the status of the value associated with this <CODE>SnmpVarBind</CODE> as a <CODE>String</CODE>.
     * This value is a displayable representation of the status integer value.
     * It is one of <CODE>Value not initialized</CODE>, <CODE>Valid Value</CODE>, <CODE>No such object</CODE>,
     * <CODE>No such Instance</CODE>, <CODE>End of Mib View</CODE>.
     * @return The status of the associated value.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public int getValueStatus() {

    /**
     * Returns the status of the value associated with this <CODE>SnmpVarBind</CODE> as an integer.
     * This value is one of {@link #stValueUnspecified}, {@link #stValueOk}, {@link #stValueNoSuchObject},
     * {@link #stValueNoSuchInstance}, {@link #stValueEndOfMibView}.
     * @return The status of the associated value.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpOidRecord resolveVarName(String name) throws SnmpStatusException {

    /**
     * Consults the MIB table storage to resolve the name to its OID type structure.
     * @param name The MIB variable name or a dot-formatted OID <CODE>String</CODE>.
     * @return The <CODE>SnmpOidRecord</CODE> object containing information on the MIB variable.
     * @exception SnmpStatusException An error occurred while resolving the MIB variable name.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpStringFixedValue(String val) {

    /**
     * Sets the <CODE>SnmpStringFixed</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified string value.
     * The status is updated to indicate that the value is valid.
     * @param val The new string value.
     * @see SnmpStringFixed
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpStringFixed getSnmpStringFixedValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpStringFixed</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpOpaqueValue(byte[] val) {

    /**
     * Sets the <CODE>SnmpOpaque</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified bytes array values.
     * The status is updated to indicate that the value is valid.
     * @param val The new bytes array value.
     * @see SnmpOpaque
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpOpaque getSnmpOpaqueValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpOpaque</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpStringValue(String val) {

    /**
     * Sets the <CODE>SnmpString</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified string value.
     * The status is updated to indicate that the value is valid.
     * @param val The new string value.
     * @see SnmpString
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpString getSnmpStringValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpString</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpIpAddressValue(String val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpIpAddress</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified ipAddress value.
     * The status is updated to indicate that the value is valid.
     * @param val The new IP address value.
     * @exception IllegalArgumentException The specified value does not correspond to an IP address.
     * @see SnmpIpAddress
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpIpAddress getSnmpIpAddressValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpIpAddress</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpOidValue(String val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpOid</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified OID value.
     * The status is updated to indicate that the value is valid.
     * @param val The new OID value.
     * @exception IllegalArgumentException The specified value is neither a numeric <CODE>String</CODE>
     * nor a <CODE>String</CODE> of the MIB database.
     * @see SnmpOid
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpOid getSnmpOidValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpOid</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpTimeticksValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpTimeticks</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified timeticks value.
     * The status is updated to indicate that the value is valid.
     * @param val The new timeticks value.
     * @exception IllegalArgumentException The specified value is negative or larger than
     * <CODE>SnmpUnsignedInt.MAX_VALUE</CODE>.
     * @see SnmpTimeticks
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpTimeticks getSnmpTimeticksValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpTimeticks</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpGaugeValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpGauge</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified gauge value.
     * The status is updated to indicate that the value is valid.
     * @param val The new gauge value.
     * @exception IllegalArgumentException The specified value is negative or larger than
     * <CODE>SnmpUnsignedInt.MAX_VALUE</CODE>.
     * @see SnmpGauge
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpGauge getSnmpGaugeValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpGauge</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpCounterValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpCounter</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified counter value.
     * The status is updated to indicate that the value is valid.
     * @param val The new counter value.
     * @exception IllegalArgumentException The specified value is negative or larger than
     * <CODE>SnmpUnsignedInt.MAX_VALUE</CODE>.
     * @see SnmpCounter
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpCounter getSnmpCounterValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpCounter</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpIntValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpInt</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified integer value.
     * The status is updated to indicate that the value is valid.
     * @param val The new integer value.
     * @exception IllegalArgumentException The specified value is smaller than <CODE>Integer.MIN_VALUE</CODE>
     * or larger than <CODE>Integer.MAX_VALUE</CODE>.
     * @see SnmpInt
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpInt getSnmpIntValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpInt</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpCounter64Value(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpCounter64</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified counter 64 value.
     * The status is updated to indicate that the value is valid.
     * @param val The new counter 64 value.
     * @exception IllegalArgumentException The specified value is negative or larger than <CODE>Long.MAX_VALUE</CODE>.
     * @see SnmpCounter64
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpCounter64 getSnmpCounter64Value() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpCounter64</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpValue(SnmpValue val) {

    /**
     * Sets the <CODE>SnmpValue</CODE> part associated with this <CODE>SnmpVarBind</CODE> with the specified value.
     * The status is updated to indicate that the value is valid.
     * @param val The new value.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final synchronized public SnmpValue getSnmpValue() {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpValue</CODE> for this variable.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setOid(SnmpOid oid) {

    /**
     * Sets the <CODE>SnmpOid</CODE> part associated with this <CODE>SnmpVarBind</CODE> with the specified OID.
     * The value part of this <CODE>SnmpVarBind</CODE> will automatically be nulled.
     * @param oid The new OID.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpOid getOid() {

    /**
     * Returns the complete OID part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpOid</CODE> for this variable.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind(String name) throws SnmpStatusException {

    /**
     * Constructs a new <CODE>SnmpVarBind</CODE> object from the specified <CODE>String</CODE> value.
     * If the name is a MIB variable, it resolves the name with the MIB database.
     * @param name The MIB variable name or a dot-formatted OID <CODE>String</CODE>.
     * @exception SnmpStatusException An error occurred while resolving the MIB variable name.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind(SnmpOid oid, SnmpValue val) {

    /**
     * Constructs a new <CODE>SnmpVarBind</CODE> object from the specified <CODE>SnmpOid</CODE> and
     * <CODE>SnmpValue</CODE>.
     * @param oid The OID part of the <CODE>SnmpVarBind</CODE>.
     * @param val The value part of the <CODE>SnmpVarBind</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind(SnmpOid oid) {

    /**
     * Constructs a new <CODE>SnmpVarBind</CODE> object from the specified <CODE>SnmpOid</CODE> value.
     * @param oid The OID part of the <CODE>SnmpVarBind</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind() {

    /**
     * Default constructor.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public int status = stValueUnspecified ;

    /**
     * Indicates the status of the value in this <CODE>SnmpVarBind</CODE>.
     * The default value is <CODE>stValueUnspecified</CODE>.
     * This attribute is updated internally and should not be changed otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpValue value = null ;

    /**
     * The value of the <CODE>SnmpVarBind</CODE>.
     * The default value is null.
     * <p><b>Reserved for internal use:</b><br>
     * As of Java Dynamic Management Kit 5.0, use instead <CODE>getSnmpValue</CODE> and <CODE>setSnmpValue</CODE></p>
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpOid oid = null ;

    /**
     * The OID of the <CODE>SnmpVarBind</CODE>.
     * The default value is null.
     * <p><b>Reserved for internal use:</b><br>
     * As of Java Dynamic Management Kit 5.0, use instead <CODE>getOid</CODE> and <CODE>setOid</CODE></p>
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public final static SnmpNull endOfMibView   = new SnmpNull(errEndOfMibViewTag) ;

    /**
     * Error code value as defined in RFC 1448 for: <CODE>endOfMibView</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public final static SnmpNull noSuchInstance = new SnmpNull(errNoSuchInstanceTag) ;

    /**
     * Error code value as defined in RFC 1448 for: <CODE>noSuchInstance</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public final static SnmpNull noSuchObject   = new SnmpNull(errNoSuchObjectTag) ;

    /**
     * Error code value as defined in RFC 1448 for: <CODE>noSuchObject</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueEndOfMibView = 5 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is <CODE>endOfMibView</CODE>.
     * Status of <CODE>SnmpVarBind</CODE> as returned by the SNMPv2 agent.
     * In the SNMPv1 context, this is appropriate when <CODE>noSuchName</CODE> is returned in response to the
     * <CODE>SnmpGetNext</CODE> request.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueNoSuchInstance = 4 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is
     * <CODE>noSuchInstance</CODE>.
     * Status of <CODE>SnmpVarBind</CODE> as returned by the SNMPv2 agent.
     * In the SNMPv1 context, this is appropriate when <CODE>noSuchName</CODE> is returned in response to the
     * <CODE>SnmpGet</CODE> request.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueNoSuchObject = 3 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is <CODE>noSuchObject</CODE>.
     * Status of <CODE>SnmpVarBind</CODE> as returned by the SNMPv2 agent.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueOk = 2 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is valid.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueUnspecified = 1 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is not initialized.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final private String statusLegend[] = { "Status Mapper", "Value not initialized",

    /**
     * Keeps the legend for the value part of the <CODE>SnmpVarBind</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
public class SnmpVarBind implements SnmpDataTypeEnums, Cloneable, Serializable {

/**
 * This class holds information for a MIB variable contained in an {@link com.sun.jmx.snmp.SnmpVarBindList}.
 * An <CODE>SnmpVarBind</CODE> consists of three parts:<P>
 * <DL>
 * <DD>- The corresponding OID object for the MIB variable.
 * <DD>- The value part associated with that OID instance.
 * If present, it determines the MIB syntax for the object.
 * <DD>- The status of the <CODE>SnmpVarBind</CODE> which specifies whether the agent responded with an
 * exception condition for this variable such as <CODE>noSuchInstance</CODE>, <CODE>endOfMibView</CODE>,
 * or <CODE>noSuchObject</CODE>.
 * </DL>
 * <p><b>This API is a Sun Microsystems internal API  and is subject
 * to change without notice.</b></p>
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    private void setValueValid() {

    /**
     * Sets the status to indicate that the value for this <CODE>SnmpVarBind</CODE> is valid.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    @Override

     /**
     * Returns the printable ASCII representation of this <CODE>SnmpVarBind</CODE>.
     * @return The printable ASCII representation.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setEndOfMibView() {

    /**
     * Set the value to {@link #endOfMibView}. This is equivalent to
     * <code>setSnmpValue(SnmpVarBind.endOfMibView)</code>.
     **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setNoSuchInstance() {

    /**
     * Set the value to {@link #noSuchInstance}. This is equivalent to
     * <code>setSnmpValue(SnmpVarBind.noSuchInstance)</code>.
     **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setNoSuchObject() {

    /**
     * Set the value to {@link #noSuchObject}. This is equivalent to
     * <code>setSnmpValue(SnmpVarBind.noSuchObject)</code>.
     **/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public String getStringValue() {

    /**
     * Returns the printable ASCII representation for the corresponding variable value.
     * @return The printable ASCII representation.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    @Override

    /**
     * Clones the SNMP variable (including value).
     * @return The SNMP variable clone.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public Object cloneWithoutValue() {

    /**
     * Clones the SNMP variable. It does not clone the value portion.
     * @return A new object with the value part set to null.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void copyValue(SnmpVarBind var) {

    /**
     * Clones and copies only the value part from another <CODE>SnmpVarBind</CODE> object.
     * @param var The <CODE>SnmpVarBind</CODE> clone.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void copyValueAndOid(SnmpVarBind var) {

    /**
     * Clones and copies the OID and value part from another <CODE>SnmpVarBind</CODE> object.
     * @param var The <CODE>SnmpVarBind</CODE> clone.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public synchronized boolean hasVarBindException() {

    /**
     * Determines whether the <CODE>SnmpVarBind</CODE> has an SNMP exception
     * (generated by agent in response to a request).
     * @return <CODE>true</CODE> if the <CODE>SnmpVarBind</CODE> has an SNMP response exception,
     * <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void appendInOid(SnmpOid oid) {

    /**
     * Appends the specified <CODE>SnmpOid</CODE> to the end of the OID of this <CODE>SnmpVarBind</CODE>.
     * @param oid The OID to append.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public void insertInOid(int oid) {

    /**
     * Inserts a sub-id at the beginning of the OID of this <CODE>SnmpVarBind</CODE>.
     * @param oid The sub-id to insert.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void addInstance(String inst) throws SnmpStatusException {

    /**
     * Adds an instance part to the OID in the <CODE>SnmpOid</CODE> object.
     * Note that there is no <CODE>getInstance</CODE> method.
     * This method will directly add the instance to the <CODE>SnmpOid</CODE> object.
     * @param inst Dot-formatted sub-identifier <CODE>String</CODE> to be appended to the OID.
     * @exception SnmpStatusException An error occurred while accessing a MIB node.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void addInstance(long[] inst) throws SnmpStatusException {

    /**
     * Adds an instance part to the OID in the <CODE>SnmpOid</CODE> object.
     * Note that there is no <CODE>getInstance</CODE> method.
     * This method will directly add the instance to the <CODE>SnmpOid</CODE> object.
     * @param inst The sub-identifier array to be appended to the OID.
     * @exception SnmpStatusException An error occurred while accessing a MIB node.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void addInstance(long inst) {

    /**
     * Adds an instance part to the OID in the <CODE>SnmpOid</CODE> object.
     * Note that there is no <CODE>getInstance</CODE> method.
     * This method will directly add the instance to the <CODE>SnmpOid</CODE> object.
     * @param inst The sub-identifier to be appended to the OID.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public boolean isOidEqual(SnmpVarBind var) {

    /**
     * Checks whether the OID for this variable completely matches the OID part of the specified
     * <CODE>SnmpVarBind</CODE> object.
     * @param var The object whose OID part is to be matched.
     * @return <CODE>true</CODE> if the OID part matches exactly, <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void clearValue() {

    /**
     * Clears the value associated with this <CODE>SnmpVarBind</CODE> and sets the status to
     * <CODE>stValueUnspecified</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public boolean isUnspecifiedValue() {

    /**
     * Checks whether the value associated with this <CODE>SnmpVarBind</CODE> is unspecified.
     * @return <CODE>true</CODE> if the status is unspecified, <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public boolean isValidValue() {

    /**
     * Checks whether the object contains a valid accessible value.
     * @return <CODE>true</CODE> if the associated value is valid, <CODE>false</CODE> otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public String getValueStatusLegend() {

    /**
     * Returns the status of the value associated with this <CODE>SnmpVarBind</CODE> as a <CODE>String</CODE>.
     * This value is a displayable representation of the status integer value.
     * It is one of <CODE>Value not initialized</CODE>, <CODE>Valid Value</CODE>, <CODE>No such object</CODE>,
     * <CODE>No such Instance</CODE>, <CODE>End of Mib View</CODE>.
     * @return The status of the associated value.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public int getValueStatus() {

    /**
     * Returns the status of the value associated with this <CODE>SnmpVarBind</CODE> as an integer.
     * This value is one of {@link #stValueUnspecified}, {@link #stValueOk}, {@link #stValueNoSuchObject},
     * {@link #stValueNoSuchInstance}, {@link #stValueEndOfMibView}.
     * @return The status of the associated value.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpOidRecord resolveVarName(String name) throws SnmpStatusException {

    /**
     * Consults the MIB table storage to resolve the name to its OID type structure.
     * @param name The MIB variable name or a dot-formatted OID <CODE>String</CODE>.
     * @return The <CODE>SnmpOidRecord</CODE> object containing information on the MIB variable.
     * @exception SnmpStatusException An error occurred while resolving the MIB variable name.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpStringFixedValue(String val) {

    /**
     * Sets the <CODE>SnmpStringFixed</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified string value.
     * The status is updated to indicate that the value is valid.
     * @param val The new string value.
     * @see SnmpStringFixed
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpStringFixed getSnmpStringFixedValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpStringFixed</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpOpaqueValue(byte[] val) {

    /**
     * Sets the <CODE>SnmpOpaque</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified bytes array values.
     * The status is updated to indicate that the value is valid.
     * @param val The new bytes array value.
     * @see SnmpOpaque
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpOpaque getSnmpOpaqueValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpOpaque</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpStringValue(String val) {

    /**
     * Sets the <CODE>SnmpString</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified string value.
     * The status is updated to indicate that the value is valid.
     * @param val The new string value.
     * @see SnmpString
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpString getSnmpStringValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpString</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpIpAddressValue(String val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpIpAddress</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified ipAddress value.
     * The status is updated to indicate that the value is valid.
     * @param val The new IP address value.
     * @exception IllegalArgumentException The specified value does not correspond to an IP address.
     * @see SnmpIpAddress
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpIpAddress getSnmpIpAddressValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpIpAddress</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpOidValue(String val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpOid</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified OID value.
     * The status is updated to indicate that the value is valid.
     * @param val The new OID value.
     * @exception IllegalArgumentException The specified value is neither a numeric <CODE>String</CODE>
     * nor a <CODE>String</CODE> of the MIB database.
     * @see SnmpOid
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpOid getSnmpOidValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpOid</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpTimeticksValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpTimeticks</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified timeticks value.
     * The status is updated to indicate that the value is valid.
     * @param val The new timeticks value.
     * @exception IllegalArgumentException The specified value is negative or larger than
     * <CODE>SnmpUnsignedInt.MAX_VALUE</CODE>.
     * @see SnmpTimeticks
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpTimeticks getSnmpTimeticksValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpTimeticks</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpGaugeValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpGauge</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified gauge value.
     * The status is updated to indicate that the value is valid.
     * @param val The new gauge value.
     * @exception IllegalArgumentException The specified value is negative or larger than
     * <CODE>SnmpUnsignedInt.MAX_VALUE</CODE>.
     * @see SnmpGauge
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpGauge getSnmpGaugeValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpGauge</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpCounterValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpCounter</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified counter value.
     * The status is updated to indicate that the value is valid.
     * @param val The new counter value.
     * @exception IllegalArgumentException The specified value is negative or larger than
     * <CODE>SnmpUnsignedInt.MAX_VALUE</CODE>.
     * @see SnmpCounter
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpCounter getSnmpCounterValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpCounter</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpIntValue(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpInt</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified integer value.
     * The status is updated to indicate that the value is valid.
     * @param val The new integer value.
     * @exception IllegalArgumentException The specified value is smaller than <CODE>Integer.MIN_VALUE</CODE>
     * or larger than <CODE>Integer.MAX_VALUE</CODE>.
     * @see SnmpInt
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpInt getSnmpIntValue() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpInt</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpCounter64Value(long val) throws IllegalArgumentException {

    /**
     * Sets the <CODE>SnmpCounter64</CODE> value part associated with this <CODE>SnmpVarBind</CODE>
     * with the specified counter 64 value.
     * The status is updated to indicate that the value is valid.
     * @param val The new counter 64 value.
     * @exception IllegalArgumentException The specified value is negative or larger than <CODE>Long.MAX_VALUE</CODE>.
     * @see SnmpCounter64
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpCounter64 getSnmpCounter64Value() throws ClassCastException {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpCounter64</CODE> value for this variable.
     * @exception ClassCastException An attempt has been made to cast an object to a subclass of which
     * it is not an instance.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setSnmpValue(SnmpValue val) {

    /**
     * Sets the <CODE>SnmpValue</CODE> part associated with this <CODE>SnmpVarBind</CODE> with the specified value.
     * The status is updated to indicate that the value is valid.
     * @param val The new value.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final synchronized public SnmpValue getSnmpValue() {

    /**
     * Returns the value part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpValue</CODE> for this variable.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public void setOid(SnmpOid oid) {

    /**
     * Sets the <CODE>SnmpOid</CODE> part associated with this <CODE>SnmpVarBind</CODE> with the specified OID.
     * The value part of this <CODE>SnmpVarBind</CODE> will automatically be nulled.
     * @param oid The new OID.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    final public SnmpOid getOid() {

    /**
     * Returns the complete OID part associated with this <CODE>SnmpVarBind</CODE>.
     * @return The <CODE>SnmpOid</CODE> for this variable.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind(String name) throws SnmpStatusException {

    /**
     * Constructs a new <CODE>SnmpVarBind</CODE> object from the specified <CODE>String</CODE> value.
     * If the name is a MIB variable, it resolves the name with the MIB database.
     * @param name The MIB variable name or a dot-formatted OID <CODE>String</CODE>.
     * @exception SnmpStatusException An error occurred while resolving the MIB variable name.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind(SnmpOid oid, SnmpValue val) {

    /**
     * Constructs a new <CODE>SnmpVarBind</CODE> object from the specified <CODE>SnmpOid</CODE> and
     * <CODE>SnmpValue</CODE>.
     * @param oid The OID part of the <CODE>SnmpVarBind</CODE>.
     * @param val The value part of the <CODE>SnmpVarBind</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind(SnmpOid oid) {

    /**
     * Constructs a new <CODE>SnmpVarBind</CODE> object from the specified <CODE>SnmpOid</CODE> value.
     * @param oid The OID part of the <CODE>SnmpVarBind</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpVarBind() {

    /**
     * Default constructor.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public int status = stValueUnspecified ;

    /**
     * Indicates the status of the value in this <CODE>SnmpVarBind</CODE>.
     * The default value is <CODE>stValueUnspecified</CODE>.
     * This attribute is updated internally and should not be changed otherwise.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpValue value = null ;

    /**
     * The value of the <CODE>SnmpVarBind</CODE>.
     * The default value is null.
     * <p><b>Reserved for internal use:</b><br>
     * As of Java Dynamic Management Kit 5.0, use instead <CODE>getSnmpValue</CODE> and <CODE>setSnmpValue</CODE></p>
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public SnmpOid oid = null ;

    /**
     * The OID of the <CODE>SnmpVarBind</CODE>.
     * The default value is null.
     * <p><b>Reserved for internal use:</b><br>
     * As of Java Dynamic Management Kit 5.0, use instead <CODE>getOid</CODE> and <CODE>setOid</CODE></p>
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public final static SnmpNull endOfMibView   = new SnmpNull(errEndOfMibViewTag) ;

    /**
     * Error code value as defined in RFC 1448 for: <CODE>endOfMibView</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public final static SnmpNull noSuchInstance = new SnmpNull(errNoSuchInstanceTag) ;

    /**
     * Error code value as defined in RFC 1448 for: <CODE>noSuchInstance</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    public final static SnmpNull noSuchObject   = new SnmpNull(errNoSuchObjectTag) ;

    /**
     * Error code value as defined in RFC 1448 for: <CODE>noSuchObject</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueEndOfMibView = 5 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is <CODE>endOfMibView</CODE>.
     * Status of <CODE>SnmpVarBind</CODE> as returned by the SNMPv2 agent.
     * In the SNMPv1 context, this is appropriate when <CODE>noSuchName</CODE> is returned in response to the
     * <CODE>SnmpGetNext</CODE> request.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueNoSuchInstance = 4 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is
     * <CODE>noSuchInstance</CODE>.
     * Status of <CODE>SnmpVarBind</CODE> as returned by the SNMPv2 agent.
     * In the SNMPv1 context, this is appropriate when <CODE>noSuchName</CODE> is returned in response to the
     * <CODE>SnmpGet</CODE> request.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueNoSuchObject = 3 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is <CODE>noSuchObject</CODE>.
     * Status of <CODE>SnmpVarBind</CODE> as returned by the SNMPv2 agent.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueOk = 2 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is valid.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final public int stValueUnspecified = 1 ;

    /**
     * Useful constant indicating that the status of the <CODE>SnmpVarBind</CODE> object is not initialized.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
    static final private String statusLegend[] = { "Status Mapper", "Value not initialized",

    /**
     * Keeps the legend for the value part of the <CODE>SnmpVarBind</CODE>.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/jmx/snmp/SnmpVarBind.java
public class SnmpVarBind implements SnmpDataTypeEnums, Cloneable, Serializable {

/**
 * This class holds information for a MIB variable contained in an {@link com.sun.jmx.snmp.SnmpVarBindList}.
 * An <CODE>SnmpVarBind</CODE> consists of three parts:<P>
 * <DL>
 * <DD>- The corresponding OID object for the MIB variable.
 * <DD>- The value part associated with that OID instance.
 * If present, it determines the MIB syntax for the object.
 * <DD>- The status of the <CODE>SnmpVarBind</CODE> which specifies whether the agent responded with an
 * exception condition for this variable such as <CODE>noSuchInstance</CODE>, <CODE>endOfMibView</CODE>,
 * or <CODE>noSuchObject</CODE>.
 * </DL>
 * <p><b>This API is a Sun Microsystems internal API  and is subject
 * to change without notice.</b></p>
 */
