_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/spi/activation/RepositoryPackage/StringSeqHelper.java
abstract public class StringSeqHelper

/**
* com/sun/corba/se/spi/activation/RepositoryPackage/StringSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/spi/activation/RepositoryPackage/StringSeqHelper.java
abstract public class StringSeqHelper

/**
* com/sun/corba/se/spi/activation/RepositoryPackage/StringSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/StringSeqHelper.java
/** An array of Strings */

/**
* org/omg/CORBA/StringSeqHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/CORBAX.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
