_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/TAG_POLICIES.java
  public static final int value = (int)(2L);

  /**
     * A profile component containing the sequence of QoS policies exported
     * with the object reference by an object adapter.
     */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/TAG_POLICIES.java


/**
* org/omg/IOP/TAG_POLICIES.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
