_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/spi/ior/TaggedComponent.java
public interface TaggedComponent extends Identifiable

/** Generic interface for all tagged components.  Users of the ORB may
* create implementations of this class and also corresponding factories
* of type TaggedComponentFactory.  The factories can be registered with an
* ORB instance, in which case they will be used to unmarshal IORs containing
* the registered tagged component.
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//com/sun/corba/se/spi/ior/TaggedComponent.java
public interface TaggedComponent extends Identifiable

/** Generic interface for all tagged components.  Users of the ORB may
* create implementations of this class and also corresponding factories
* of type TaggedComponentFactory.  The factories can be registered with an
* ORB instance, in which case they will be used to unmarshal IORs containing
* the registered tagged component.
*/
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/TaggedComponent.java
  public byte component_data[] = null;

  /** The component data associated with the component id. */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/TaggedComponent.java
  public int tag = (int)0;

  /** The tag, represented as a component id. */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/IOP/TaggedComponent.java
public final class TaggedComponent implements org.omg.CORBA.portable.IDLEntity

/**
* org/omg/IOP/TaggedComponent.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
