_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ThreadPolicyOperations.java
  org.omg.PortableServer.ThreadPolicyValue value ();

  /**
	 * specifies the policy value
	 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ThreadPolicyOperations.java
public interface ThreadPolicyOperations  extends org.omg.CORBA.PolicyOperations

/**
	 * The ThreadPolicy specifies the threading model 
	 * used with the created POA. The default is 
	 * ORB_CTRL_MODEL.
	 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/PortableServer/ThreadPolicyOperations.java


/**
* org/omg/PortableServer/ThreadPolicyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Tuesday, October 6, 2015 4:40:34 PM PDT
*/
