_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/UnionMemberHelper.java
abstract public class UnionMemberHelper

/**
* The Helper for <tt>UnionMember</tt>.  For more information on
* Helper files, see <a href="doc-files/generatedfiles.html#helper">
* "Generated Files: Helper Files"</a>.<P>
* org/omg/CORBA/UnionMemberHelper.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from ir.idl
* 03 June 1999 11:33:43 o'clock GMT+00:00
*/
