_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/UnknownUserExceptionHolder.java
public final class UnknownUserExceptionHolder implements org.omg.CORBA.portable.Streamable

/**
* The Holder for <tt>UnknownUserException</tt>.  For more information on
* Holder files, see <a href="doc-files/generatedfiles.html#holder">
* "Generated Files: Holder Files"</a>.<P>
* org/omg/CORBA/UnknownUserExceptionHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from CORBA.idl
* Thursday, August 24, 2000 5:52:22 PM PDT
*/
