_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/NamingContextExtPackage/URLStringHelper.java
abstract public class URLStringHelper

/**
 * URLString is the URL address (corbaloc: or corbaname:) represented as
 * a String.
 */
_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CosNaming/NamingContextExtPackage/URLStringHelper.java


/**
* org/omg/CosNaming/NamingContextExtPackage/URLStringHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/workspace/8-2-build-windows-amd64-cygwin/jdk8u65/4987/corba/src/share/classes/org/omg/CosNaming/nameservice.idl
* Tuesday, October 6, 2015 4:40:33 PM PDT
*/
