_func_
jdk
c:/Users/saahil claypool/Documents/JDKSource//org/omg/CORBA/WCharSeqHolder.java
public final class WCharSeqHolder implements org.omg.CORBA.portable.Streamable

/**
* The Holder for <tt>WCharSeq</tt>.  For more information on
* Holder files, see <a href="doc-files/generatedfiles.html#holder">
* "Generated Files: Holder Files"</a>.<P>
* org/omg/CORBA/WCharSeqHolder.java
* Generated by the IDL-to-Java compiler (portable), version "3.0"
* from streams.idl
* 13 May 1999 22:41:36 o'clock GMT+00:00
*/
